name: 创建用户脚本

on:
  workflow_dispatch:
  push:
    paths:
      - 'tampermonkey/manifest.json'

jobs:
  build:
    name: Build UserJS
    runs-on: ubuntu-latest
    steps:
    - name: 检查仓库
      uses: actions/checkout@v3
      
    - name: 安装 Node.js
      uses: actions/setup-node@v3

    - name: 更新 NPM
      run: npm update

    - name: 安装 NPM 依赖
      run: npm install
      
    - name: 创建脚本
      run: npm run tampermonkey
      
    - name: 上传文件
      uses: actions/upload-artifact@v4
      with:
        name: Bilibili-Old.user.js
        path: tampermonkey/main.user.js
        retention-days: 30
